groups:
  - name: Pege access 3 times for 5 minutes
    rules:
      - alert: PageAccess3TimesFor5Minutes
        expr: changes(http_request_duration_seconds_count[5m]) >= 3
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Page was accessed more than 3 times within last 5 minutes"